[workspace]
members = ["ast", "lexer", "parser", "hir", "database", "runtime", "web", "forms", "cli"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
serde_json = "1.0"
rand_core = { version = "0.6", features = ["getrandom"] }
semver = "1.0"
sha2 = "0.10"
mysql = { version = "28.0.3", default-features = false, features = ["minimal-rust", "rustls-tls-ring"] }
r2d2 = "0.8.10"
ureq = { version = "3.4.2", default-features = true }
lettre = { version = "0.11.23", default-features = false, features = ["builder", "smtp-transport", "rustls", "ring", "webpki-roots"] }
ring = "0.17.14"
zeroize = "1.9.0"
url = "2.5.8"
zelyra-ast = { path = "ast", version = "0.3" }
zelyra-lexer = { path = "lexer", version = "0.3" }
zelyra-parser = { path = "parser", version = "0.3" }
zelyra-hir = { path = "hir", version = "0.3" }
zelyra-database = { path = "database", version = "0.3" }
zelyra-runtime = { path = "runtime", version = "0.3" }
zelyra-web = { path = "web", version = "0.3" }
zelyra-forms = { path = "forms", version = "0.3" }
