[project]
name = "zelyra"
version = "0.1.25"
zelyra = "0.1"

[database.main]
engine = "mariadb"

[capabilities]
database = true
network = true
clock = true
environment = true
random = true
filesystem = true
