#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_dir="$(cd -- "${script_dir}/.." && pwd)"
fixture_dir="${script_dir}/fixtures"
zelyra_bin="${ZELYRA_BIN:-${repo_dir}/target/debug/zelyra}"
configured_url="${DATABASE_URL:-}"

if [[ -z "${configured_url}" ]]; then
    echo "error: set DATABASE_URL to a local zelyra_ci or zelyra_test PostgreSQL database URL" >&2
    exit 1
fi
if [[ ! -x "${zelyra_bin}" ]]; then
    echo "error: Zelyra binary not found at ${zelyra_bin}; run cargo build -p zelyra-cli first" >&2
    exit 1
fi
if ! command -v psql >/dev/null 2>&1; then
    echo "error: psql is required for PostgreSQL schema safety integration tests" >&2
    exit 1
fi

case "${configured_url}" in
    postgres://*) scheme="postgres" ;;
    postgresql://*) scheme="postgresql" ;;
    *)
        echo "error: PostgreSQL safety URL must use postgres:// or postgresql://" >&2
        exit 1
        ;;
esac
connection="${configured_url#*://}"
authority="${connection%%/*}"
database_path="${connection#*/}"
base_database="${database_path%%\?*}"
host_port="${authority##*@}"
if [[ "${host_port}" =~ ^\[([^]]+)\](:[0-9]+)?$ ]]; then
    host="${BASH_REMATCH[1]}"
else
    host="${host_port%%:*}"
fi

if [[ "${host}" != "127.0.0.1" && "${host}" != "localhost" && "${host}" != "::1" ]] || \
    [[ "${base_database}" != "zelyra_ci" && "${base_database}" != "zelyra_test" ]] || \
    [[ "${database_path}" != "${base_database}" ]]; then
    echo "error: PostgreSQL safety test is restricted to local zelyra_ci or zelyra_test databases without URL parameters" >&2
    exit 1
fi

base_url="${scheme}://${authority}/${base_database}"
test_database="zelyra_schema_safety_$$"
test_url="${scheme}://${authority}/${test_database}"
database_created=false

cleanup() {
    if [[ "${database_created}" == true ]]; then
        psql -X -v ON_ERROR_STOP=1 --dbname="${base_url}" \
            --command="DROP DATABASE IF EXISTS \"${test_database}\";" >/dev/null 2>&1 || true
    fi
}
trap cleanup EXIT

if ! psql -X -v ON_ERROR_STOP=1 --dbname="${base_url}" \
    --command="CREATE DATABASE \"${test_database}\";" >/dev/null 2>&1; then
    echo "error: could not create the isolated PostgreSQL schema-safety database" >&2
    exit 1
fi
database_created=true

before="${fixture_dir}/schema_safety_metadata_before_postgres.zyl"
after="${fixture_dir}/schema_safety_metadata_after_postgres.zyl"

echo "[PostgreSQL] create isolated schema and verify serial metadata"
DATABASE_URL="${test_url}" "${zelyra_bin}" db apply "${before}" >/dev/null

psql -X -v ON_ERROR_STOP=1 --dbname="${test_url}" \
    --command='DROP TABLE public.identity_records;' >/dev/null
psql -X -v ON_ERROR_STOP=1 --dbname="${test_url}" \
    --command='CREATE TABLE public.identity_records (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);' >/dev/null

initial_plan="$(DATABASE_URL="${test_url}" "${zelyra_bin}" db plan "${before}")"
grep -Fq "No schema changes." <<<"${initial_plan}"
echo "[PostgreSQL] serial and identity columns are recognized without false drift"

psql -X -v ON_ERROR_STOP=1 --dbname="${test_url}" \
    --command='ALTER TABLE public.detached_sequence_records ALTER COLUMN id DROP DEFAULT;' >/dev/null
orphaned_sequence_plan="$(DATABASE_URL="${test_url}" "${zelyra_bin}" db plan "${before}")"
grep -Fq "[UNSUPPORTED] change auto-increment status of detached_sequence_records.id" <<<"${orphaned_sequence_plan}"

psql -X -v ON_ERROR_STOP=1 --dbname="${test_url}" \
    --command="INSERT INTO public.pg_metadata_records(active, name) VALUES (false, 'retained');" >/dev/null

metadata_plan="$(DATABASE_URL="${test_url}" "${zelyra_bin}" db plan "${after}")"
for expected_change in \
    "[UNSUPPORTED] change primary-key status of pg_metadata_records.id" \
    "[UNSUPPORTED] change auto-increment status of pg_metadata_records.id" \
    "[UNSUPPORTED] change auto-increment status of detached_sequence_records.id" \
    "[UNSUPPORTED] change default of pg_metadata_records.active" \
    "[UNSUPPORTED] change default of pg_metadata_records.name"; do
    if ! grep -Fq "${expected_change}" <<<"${metadata_plan}"; then
        echo "error: expected PostgreSQL plan entry was missing: ${expected_change}" >&2
        printf '%s\n' "${metadata_plan}" >&2
        exit 1
    fi
done

if output="$(DATABASE_URL="${test_url}" "${zelyra_bin}" db apply "${after}" --allow-risky 2>&1)"; then
    echo "error: PostgreSQL applied schema metadata drift marked unsupported" >&2
    exit 1
fi
if ! grep -Fq "error[E-DB-006]" <<<"${output}"; then
    echo "error: PostgreSQL refused the change for an unexpected reason" >&2
    printf '%s\n' "${output}" >&2
    exit 1
fi

metadata_state_sql="
    SELECT concat(
        (SELECT count(*)::text FROM public.pg_metadata_records WHERE name = 'retained'),
        ':',
        (SELECT count(*)::text FROM pg_constraint
            WHERE conrelid = 'public.pg_metadata_records'::regclass AND contype = 'p'),
        ':',
        (pg_get_serial_sequence('public.pg_metadata_records', 'id') IS NOT NULL)::text,
        ':',
        (SELECT (column_default IS NULL)::text FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'pg_metadata_records' AND column_name = 'active'),
        ':',
        (SELECT (column_default IS NULL)::text FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'pg_metadata_records' AND column_name = 'name'),
        ':',
        (pg_get_serial_sequence('public.detached_sequence_records', 'id') IS NOT NULL)::text,
        ':',
        (SELECT (column_default IS NULL)::text FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'detached_sequence_records' AND column_name = 'id')
    );
"
metadata_state="$(psql -X -At --dbname="${test_url}" --command="${metadata_state_sql}")"
if [[ "${metadata_state}" != "1:1:true:false:false:true:true" ]]; then
    echo "error: PostgreSQL schema or retained data changed after refusal (state ${metadata_state})" >&2
    exit 1
fi
echo "[PostgreSQL] default, primary-key, and identity drift is detected and refused"
