[package]
name = "zelyra-database"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
fuzzing = []

[dependencies]
mysql.workspace = true
r2d2.workspace = true
sha2.workspace = true
zelyra-ast.workspace = true

[dev-dependencies]
zelyra-lexer.workspace = true
zelyra-parser.workspace = true
